# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackPoint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackPoint
  pod 'Charts'

  target 'TrackPointTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackPointUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackPointUITests1' do
    inherit! :search_paths
    # Pods for testing
  end

end
